# Fork from P3TERX's GitHub Actions, modified by Ivan Liao on July 29, 2020
#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build MT1300 from GL-iNet

on:
  repository_dispatch:
  release:
    types: published

  push:
    branches:
      - main
    paths:
      - '.config.gl'

#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  REPO_OP: https://github.com/gl-inet/openwrt.git
  REPO_LEDE: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: openwrt-19.07.2
  FEEDS_CONF: feeds.conf.default
  PATCH_PATH: patch
  CONFIG_FILE: .config.gl
  CUSTOM_CONFIG: customize.sh
  #SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_OP -b $REPO_BRANCH openwrt
        git clone $REPO_LEDE -b master lede
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        ln -sf /workdir/lede $GITHUB_WORKSPACE/lede
        
    - name: Update and install LEDE feeds
      run: cd /workdir/lede && ./scripts/feeds update -a && ./scripts/feeds install -a
        
    - name: Update and install OpenWrt feeds
      run: cd /workdir/openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a
  
    - name: Load custom feeds
      run: |
        cd /workdir
        mkdir -p /workdir/openwrt/package/lean

        # Add luci-app-ssr-plus
        cd /workdir/openwrt/package/lean
        git clone --depth=1 https://github.com/fw876/helloworld
        cd /workdir/openwrt

        cd /workdir/lede/package/lean
        cp -rp shadowsocksr-libev /workdir/openwrt/package/lean/
        cp -rp pdnsd-alt /workdir/openwrt/package/lean/
        cp -rp microsocks /workdir/openwrt/package/lean/
        cp -rp dns2socks /workdir/openwrt/package/lean/
        cp -rp simple-obfs /workdir/openwrt/package/lean/
        cp -rp v2ray-plugin /workdir/openwrt/package/lean/
        cp -rp v2ray /workdir/openwrt/package/lean/
        cp -rp xray /workdir/openwrt/package/lean/
        cp -rp trojan /workdir/openwrt/package/lean/
        cp -rp ipt2socks /workdir/openwrt/package/lean/
        cp -rp redsocks2 /workdir/openwrt/package/lean/
        cp -rp kcptun /workdir/openwrt/package/lean/

        cd /workdir/openwrt
        mv /workdir/openwrt/feeds/gli_pub/shadowsocks-libev /workdir/openwrt/feeds/gli_pub/shadowsocks-libev.bak
        mv /workdir/openwrt/feeds/packages/net/shadowsocks-libev /workdir/openwrt/feeds/packages/net/shadowsocks-libev.bak
        cp -r /workdir/lede/feeds/packages/net/shadowsocks-libev /workdir/openwrt/feeds/gli_pub/shadowsocks-libev
        cp -r /workdir/lede/feeds/packages/net/shadowsocks-libev /workdir/openwrt/feeds/packages/net/shadowsocks-libev
        cp -r /workdir/lede/feeds/packages/net/shadowsocks-libev /workdir/openwrt/package/lean/helloworld/

        # Clone community packages to package/community
        mkdir package/community
        cd /workdir/openwrt/package/community

        # Add Lienol's Packages
        git clone --depth=1 https://github.com/Lienol/openwrt-package

        # Add luci-app-passwall
        git clone --depth=1 https://github.com/xiaorouji/openwrt-passwall

        # Add gotop
        svn co https://github.com/project-openwrt/openwrt/trunk/package/ctcgfw/gotop

        # Add smartdns
        svn co https://github.com/pymumu/smartdns/trunk/package/openwrt ../smartdns
        svn co https://github.com/project-openwrt/openwrt/trunk/package/ntlf9t/luci-app-smartdns ../luci-app-smartdns

        # Add adbyby
        cp -r /workdir/lede/package/lean/adbyby ./
        cp -r /workdir/lede/package/lean/luci-app-adbyby-plus ./

    - name: Fix compile issue
      run: |
        cd /workdir/openwrt/staging_dir/host/bin
        ln -s /usr/bin/upx upx
        ln -s /usr/bin/upx-ucl upx-ucl
        ls -l upx*
        rm -rf /workdir/openwrt/feeds/packages/lang/golang
        cp -r /workdir/lede/feeds/packages/lang/golang /workdir/openwrt/feeds/packages/lang/golang
        
    - name: Load custom configuration
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $CUSTOM_CONFIG
        cd openwrt
        $GITHUB_WORKSPACE/$CUSTOM_CONFIG
        
    #- name: SSH connection to Actions
    #  uses: P3TERX/debugger-action@main
    #  if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "::set-output name=status::success"
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "::set-env name=DEVICE_NAME::_$(cat DEVICE_NAME)"
        echo "::set-env name=FILE_DATE::_$(date +"%Y%m%d%H%M")"

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin
    
    - name: Organize plugin
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        cd openwrt/bin/targets/*/*
        mkdir ssrp
        cp ../../../packages/mipsel_24kc/luci/luci_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/luci/luci-i18n-base-zh-cn_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/packages/ttyd_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/luci/luci-app-ttyd_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/packages/wget_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/luci/luci-i18n-ttyd-zh-cn_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/packages/htop_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/shadowsocksr-libev-alt_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/pdnsd-alt_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/microsocks_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/dns2socks_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/shadowsocksr-libev-ssr-local_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/simple-obfs_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/tcping_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/v2ray-plugin_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/xray_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/trojan_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/ipt2socks_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/redsocks2_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/luci-app-ssr-plus_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/base/luci-i18n-ssr-plus-zh-cn_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/luci/luci-compat_*.ipk ./ssrp/
        cp ../../../packages/mipsel_24kc/luci/luci-lib-ipkg_*.ipk ./ssrp/

        cat << EOF > ./ssrp/install-ssrp.sh
        opkg update
        opkg install luci luci-i18n-base-zh-cn ttyd luci-app-ttyd wget
        opkg install ./luci-i18n-ttyd-zh-cn_*.ipk
        opkg install ./htop_*.ipk
        opkg install ./shadowsocksr-libev-alt_*.ipk
        opkg install ./pdnsd-alt_*.ipk 
        opkg install ./microsocks_*.ipk 
        opkg install ./dns2socks_*.ipk 
        opkg install ./shadowsocksr-libev-ssr-local_*.ipk 
        opkg install ./simple-obfs_*.ipk
        opkg install ./tcping_*.ipk 
        opkg install ./v2ray-plugin_*.ipk 
        opkg install ./xray_*.ipk 
        opkg install ./trojan_*.ipk 
        opkg install ./ipt2socks_*.ipk
        opkg install ./redsocks2_*.ipk 
        opkg install ./luci-app-ssr-plus_*.ipk
        opkg install ./luci-i18n-ssr-plus-zh-cn_*.ipk
        opkg install ./luci-compat_*.ipk --force-overwrite
        opkg install ./luci-lib-ipkg_*.ipk
        EOF

        chmod +x ./ssrp/install-ssrp.sh

        tar czvf mt1300-ssrp.tar.gz ./ssrp
        rm -rf ./ssrp

    - name: Organize files
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
        
    - name: Upload firmware directory
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}
